### ISSUE TITLE
Is there a copy of nvidia 360 sdk 2.1?

### ISSUE THREAD

**Issue by leaf918** [thomasbing/Project-Ironman#1]

**Comment by rongbingzhou** [comment]
You can download it on NVIDIA website:
https://developer.nvidia.com/gameworksdownload#?search=360

**Comment by leaf918** [comment]
> You can download it on NVIDIA website:
> https://developer.nvidia.com/gameworksdownload#?search=360

Thanks,I have tried ,but nvidia has posted a notice of end support of this SDK.
If you can send a copy that ,I thanks you very much.
Regards.

**Comment by rongbingzhou** [comment]
Sorry I also don't have a copy of the NVIDIA 360 SDK 2.1. Maybe you can contact authors of the SDK for help or ask if anyone in the  NVIDIA Developer Forum has a copy of the SDK.

**Comment by leaf918** [comment]
> Sorry I also don't have a copy of the NVIDIA 360 SDK 2.1. Maybe you can contact authors of the SDK for help or ask if anyone in the NVIDIA Developer Forum has a copy of the SDK.

Thanks for your reply and suggestion.

**Comment by rongbingzhou** [comment]
No problem. Good luck!
